// Dummy dataset: Chennai spots
const PLACES = [
    {
        id: 'p1',
        name: "Murugan Idli Shop",
        description: "Famous for fluffy idlis and authentic Tamil breakfast.",
        tags: ["South Indian", "Budget", "Veg"],
        rating: 4.6,
        priceTier: 1,
        veg: true,
        lat: 13.0629,
        lng: 80.2780,
        hours: "6:30 AM - 11:00 PM",
        image: "https://c.ndtvimg.com/2019-03/g49icpdk_world-idli-day-idli-generic_625x300_29_March_19.jpg"
    },
    {
        id: 'p2',
        name: "Amethyst Café",
        description: "Garden café known for coffee, pastries, and a relaxed vibe.",
        tags: ["Cafe", "Continental", "Chill"],
        rating: 4.4,
        priceTier: 2,
        veg: true,
        lat: 13.0494,
        lng: 80.2518,
        hours: "10:00 AM - 10:00 PM",
        image: "https://images.unsplash.com/photo-1528698827591-e19ccd7bc23d?auto=format&fit=crop&w=800&q=60"
    },
    {
        id: 'p3',
        name: "Marina Beach Stalls",
        description: "Street food by the sea – sundal, bajji, and fresh corn.",
        tags: ["Street Food", "Seafood", "Budget"],
        rating: 4.2,
        priceTier: 1,
        veg: false,
        lat: 13.0492,
        lng: 80.2824,
        hours: "Evenings till late",
        image: "img/beach.jpg"
    },
    {
        id: 'p4',
        name: "Annalakshmi Restaurant",
        description: "Upscale vegetarian dining with temple-style ambience.",
        tags: ["Veg", "Fine Dining", "Indian"],
        rating: 4.7,
        priceTier: 3,
        veg: true,
        lat: 13.0830,
        lng: 80.2700,
        hours: "11:30 AM - 10:00 PM",
        image: "https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?auto=format&fit=crop&w=800&q=60"
    },
    {
        id: 'p5',
        name: "Ponnusamy Hotel",
        description: "Legendary spot for authentic Chettinad non-veg dishes.",
        tags: ["Chettinad", "Non-Veg", "Spicy"],
        rating: 4.5,
        priceTier: 2,
        veg: false,
        lat: 13.0659,
        lng: 80.2731,
        hours: "11:00 AM - 11:00 PM",
        image: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=800&q=60"
    },
    {
        id: 'p6',
        name: "Dakshin, Crowne Plaza",
        description: "Luxury dining showcasing South Indian regional cuisines.",
        tags: ["Fine Dining", "South Indian", "Luxury"],
        rating: 4.8,
        priceTier: 3,
        veg: true,
        lat: 13.0104,
        lng: 80.2209,
        hours: "12:00 PM - 11:00 PM",
        image: "https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=800&q=60"
    },
    {
        id: 'p7',
        name: "The Living Room",
        description: "Popular youth hangout restrobar",
        tags: ["Hangout","Fine Dining", "Restrobar"],
        rating: 4.3,
        priceTier: 3,
        veg: false,
        lat: 13.0007,
        lng: 80.2660,
        hours: "Open all day",
        image: "https://lh3.googleusercontent.com/p/AF1QipN8d4hSiy58c0wS-3uG6Cp3KqdSWSyXERE0B95B=s1360-w1360-h1020-rw"
    },
    {
        id: 'p8',
        name: "Sandy’s Chocolate Laboratory",
        description: "Dessert heaven with creative cakes and milkshakes.",
        tags: ["Desserts", "Cafe", "Trendy"],
        rating: 4.6,
        priceTier: 2,
        veg: true,
        lat: 13.0362,
        lng: 80.2462,
        hours: "11:00 AM - 11:00 PM",
        image: "https://images.unsplash.com/photo-1600891964599-f61ba0e24092?auto=format&fit=crop&w=800&q=60"
    },
    {
        id: 201,
        name: "Adyar Ananda Bhavan (A2B)",
        desc: "Iconic vegetarian chain famous for South Indian meals and sweets.",
        price: 2,
        rating: 4.5,
        tags: ["south indian", "vegetarian", "chain"],
        lat: 13.005,
        lng: 80.254,
        image: "img/a2b.png"
    },
    {
        id: 202,
        name: "Anjappar Chettinad",
        desc: "Authentic Chettinad cuisine from a Chennai-founded chain.",
        price: 3,
        rating: 4.4,
        tags: ["chettinad", "south indian", "non-veg"],
        lat: 13.042,
        lng: 80.227,
        image: "img/anjappar.jpeg"
    },
    {
        id: 203,
        name: "Ratna Cafe",
        desc: "Historic Triplicane fast-food chain famed for sambar-idly.",
        price: 1,
        rating: 4.3,
        tags: ["south indian", "fast food", "cheap"],
        lat: 13.082,
        lng: 80.277,
        image: "img/ratna-cafe.jpg"
    },
    {
        id: 204,
        name: "Vivaha Bhojanambu",
        desc: "Popular Andhra-style restaurant in Anna Nagar East.",
        price: 2,
        rating: 4.2,
        tags: ["andhra", "non-veg", "trending"],
        lat: 13.06603,
        lng: 80.24224,
        image: "img/vivaha-bhojanambu.jpg"
    },
    {
        id: 205,
        name: "Dindigul Thalappakatti",
        desc: "Famous biryani chain in Ashok Nagar, Chennai.",
        price: 2,
        rating: 4.0,
        tags: ["biryani", "south indian", "non-veg"],
        lat: 13.03124,
        lng: 80.21619,
        image: "img/thalappakatti.jpg"
    },
    {
        id: 206,
        name: "Sangamithirai",
        desc: "Native Tamil cuisine, highly rated local eatery.",
        price: 2,
        rating: 5.0,
        tags: ["south indian", "tamil", "local"],
        lat: 13.035,
        lng: 80.225,
        image: "img/sangamithirai.jpg"
    }
];
